export type PredictionData = {
  id: number;
  user_id: string;
  age: number;
  job: string;
  marital: string;
  education: string;
  has_credit_in_default: string;
  balance: number;
  housing: string;
  loan: string;
  contact: string;
  month: string;
  day_of_week: string;
  duration: number;
  campaign: number;
  pdays: number;
  previous: number;
  poutcome: string;
  emp_var_rate: number;
  cons_price_idx: number;
  cons_conf_idx: number;
  euribor3m: number;
  nr_employed: number;
  y: string | null;
  prediction_result: string;
  prediction_probability: number;
  created_at: string;
  updated_at: string;
};
